services:
  - type: web
    name: gitlabchatbot-private-1
    runtime: node
    plan: free
    region: oregon
    repo: https://github.com/akhil2510/gitLabChatBot_private
    branch: main
    autoDeploy: true
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: gcp-starter
      - key: PINECONE_INDEX
        value: gitlab-handbook
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: EMBEDDING_PROVIDER
        value: huggingface
      - key: FRONTEND_URL
        value: https://merry-marshmallow-b20e6a.netlify.app
